"""Private native receiver ingress and provenance-preserving PCM mixing.

This is not an output scheduler. Receiver deadlines pass through a bounded mix
and OwnTone's existing input timestamp/output machinery with a declared common
relay delay. A source-only backend flush barrier precedes each ownership grant.
"""
from __future__ import annotations

from array import array
import asyncio
from collections import deque
from dataclasses import replace
import json
import logging
import os
from pathlib import Path
import socket
import stat
import struct
import sys
import time
from uuid import UUID, uuid4

from shiri.rpc import RpcError, call_rpc
from .latency import MINIMUM_LOCAL_OUTPUT_BUFFER_MS
from .music_startup import MusicStartupTrace
from .source import SourceActor
from .speech_startup import SpeechPreparation, complete as complete_speech_startup, retire_backend
from .timing import (
    Clock, FLAG_AIRPLAY2, FLAG_GAP, FLAG_SPEECH_ONLY, FramedFifoWriter,
    HEADER_BYTES, Kind, MAX_FRAMES, Packet, RATE, RELAY_DELAY_NS, StreamFence,
    TimingError, ZERO_UUID, output_packet,
)

log = logging.getLogger(__name__)

# Match only messages generated by our timing gates. An exception originating
# in a transport or dependency can contain arbitrary text and is never logged.
_TIMING_FAULT_REASONS = {
    "Native clock mapping has no sufficiently narrow bracket": "clock_bracket",
    "Native clock mapping is stale or belongs to another clock": "clock_age",
    "Native presentation anchor exceeds the clock projection bound": "clock_projection",
    "Native presentation clock repeated, moved backwards or changed without a flush": "presentation_order",
    "Repeated or reordered native PCM": "frame_order",
    "Missing native PCM without an explicit gap marker": "frame_gap",
    "PCM belongs to an ended producer or stale flush generation": "stream_generation",
    "Native event does not carry its exact admitted source token": "source_identity",
    "Native callback belongs to a previous flush generation": "callback_generation",
    "Stale or nonconsecutive native flush generation": "flush_generation",
    "Stale native end event": "end_generation",
    "Unexpected native receiver message": "message_kind",
    "Mixed PCM source token does not match its native producer": "mixed_identity",
    "OwnTone framed output requires mapped timed PCM": "output_clock",
    "Output PCM was not armed for its exact source generation": "output_generation",
    "Timed audio FIFO changed ownership identity": "fifo_identity",
    "Atomic timed FIFO write was unexpectedly partial": "fifo_partial_write",
    "Output source barrier did not acknowledge the exact owner and operation": "barrier_ack",
    "An old native source cannot flush a successor": "flush_owner",
}


def _fault_context(exc, stage, packet, previous, *, received_bytes, now_ns):
    """Fixed numeric evidence and an allowlisted reason; no audio or identities."""
    if type(exc) is TimingError:
        reason = _TIMING_FAULT_REASONS.get(str(exc), "invalid_envelope" if stage == "decode" else "timing_invalid")
    elif isinstance(exc, TimeoutError):
        reason = "transport_timeout"
    elif isinstance(exc, OSError):
        reason = "transport_io"
    else:
        reason = "internal_failure"
    record = {"reason": reason, "stage": stage, "observed_monotonic_ns": now_ns,
              "received_bytes": received_bytes, "previous": previous}
    if packet is not None:
        record["packet"] = {
            "kind": packet.kind.name.lower(), "clock": packet.clock.name.lower(),
            "epoch": packet.epoch, "generation": packet.generation, "sequence": packet.sequence,
            "frame_index": packet.frame_index, "frames": packet.frames,
            "presentation_ns": packet.presentation_ns, "clock_sample_ns": packet.clock_sample_ns,
            "monotonic_before_ns": packet.monotonic_before_ns, "monotonic_after_ns": packet.monotonic_after_ns,
            "bracket_ns": packet.monotonic_after_ns - packet.monotonic_before_ns,
            "mapping_age_ns": now_ns - packet.monotonic_after_ns,
            "projection_ns": packet.presentation_ns - packet.clock_sample_ns,
        }
    return record


class NativeMixer:
    """Mix complete native blocks without erasing or regenerating their anchors."""
    def __init__(self, fifo: Path, *, writer=None, now_ns=time.monotonic_ns,
                 speech_output=None, relay_delay_ns=RELAY_DELAY_NS, output_buffer_ms=MINIMUM_LOCAL_OUTPUT_BUFFER_MS):
        self.writer = writer if writer is not None else FramedFifoWriter(fifo)
        self.now_ns = now_ns
        if (type(relay_delay_ns) is not int or not 0 < relay_delay_ns <= 10_000_000_000
                or type(output_buffer_ms) is not int or not MINIMUM_LOCAL_OUTPUT_BUFFER_MS <= output_buffer_ms <= 4250
                or relay_delay_ns < output_buffer_ms*1_000_000):
            raise ValueError("Native timing requires a bounded relay and output lead")
        self.speech_output = speech_output
        self.relay_delay_ns = relay_delay_ns
        self.output_buffer_ms = output_buffer_ms
        self.actor = None
        self.token = None
        self.route = None
        self.error = None
        self.speech = deque()
        self.maximum_speech_frames = RATE // 4
        self.speech_dropped_frames = 0
        self._gain = 1.0
        self._target_gain = 1.0
        self._idle_frame = 0
        self._idle_next_ns = 0
        self._idle_hold_ns = 0
        self._speech_input_until_ns = 0
        self._last_native_ns = 0
        self._last_mapping = None
        self._last_packet = None
        self.blocks = 0
        self.speech_preparation = None
        self._speech_gain = 0.28

    def fence(self, token):
        # The actor invokes this under the same lock as every final FIFO write.
        # Speech is a separate bounded queue and producer: leave both intact.
        self.token = token
        self._last_native_ns = 0
        self._last_packet = None
        self._idle_next_ns = 0
        self._idle_frame = 0

    def arm(self, owner):
        self.route = owner
        self.writer.reset(owner)

    def _send_speech(self, data, samples, gain):
        self.speech_output.set_gain(gain)
        if not self.speech_output.push(data, samples):
            raise RpcError("audio_unavailable", "Speech output refused bounded prepared PCM")
        self._speech_input_until_ns = self.now_ns()+250_000_000
        self._idle_hold_ns = self.now_ns() + (self.output_buffer_ms+600)*1_000_000

    def begin_speech_preparation(self, preparation):
        previous = self.speech_preparation
        if previous is not None and previous is not preparation and not previous.retired:
            raise RpcError("session_conflict", "Another exact speech preparation owns this room")
        self.speech_preparation = preparation

    def retire_speech_preparation(self, identity):
        preparation = self.speech_preparation
        if preparation is not None and preparation.identity is identity:
            preparation.retire()
            self.speech_output.retire(preparation.speech_id)
            return preparation

    def push_speech(self, data: bytes, samples: int):
        if type(samples) is not int or not 0 < samples <= RATE // 5 or len(data) != samples * 2:
            raise RpcError("invalid_media", "Speech audio frame has an invalid size")
        if self.speech_output is not None:
            # The private backend mixes these samples on its player thread,
            # after waiting for the music anchor. Do not put them in the early
            # native program queue or apply early ducking to queued music.
            preparation = self.speech_preparation
            if preparation is not None:
                preparation.push(data, samples, self._speech_gain, self._send_speech)
            else:
                # Existing independent unit fixtures may omit preparation; the
                # production AudioWorker establishes it before RTC callbacks.
                self._send_speech(data, samples, self._speech_gain)
            return
        values = array("h", data)
        if sys.byteorder != "little":
            values.byteswap()
        self.speech.extend(values)
        excess = len(self.speech) - self.maximum_speech_frames
        for _ in range(max(0, excess)):
            self.speech.popleft()
        self.speech_dropped_frames += max(0, excess)
        # Padding carries even a short idle utterance through OwnTone's buffers.
        # This never changes an active music owner or invokes a backend command.
        self._idle_hold_ns = self.now_ns() + self.relay_delay_ns + 500_000_000

    def set_speech_gain(self, gain):
        self._speech_gain = gain
        if self.speech_output is not None:
            self.speech_output.set_gain(gain)

    def _mix(self, pcm, frames):
        values = array("h", pcm)
        if sys.byteorder != "little":
            values.byteswap()
        for index in range(frames):
            target = self._target_gain
            step = 1.0 / (RATE * (0.04 if target < self._gain else 0.25))
            self._gain = (min(target, self._gain + step) if target > self._gain
                          else max(target, self._gain - step))
            voice = self.speech.popleft() if self.speech else 0
            for channel in (index * 2, index * 2 + 1):
                values[channel] = max(-32768, min(32767, round(values[channel] * self._gain) + voice))
        if sys.byteorder != "little":
            values.byteswap()
        return values.tobytes()

    def accept(self, packet: Packet, token):
        if self.actor is None:
            raise TimingError("Native mixer has no ownership actor")
        mapped = None
        def write():
            nonlocal mapped
            output, mapped = output_packet(packet, packet.pcm, token, now_ns=self.now_ns(),
                                           relay_delay_ns=self.relay_delay_ns)
            if self.speech_output is None:
                output = replace(output, pcm=self._mix(packet.pcm, packet.frames))
            self.writer.write(output)
            self._last_native_ns = self.now_ns()
            self._last_packet = packet
            self._last_mapping = mapped
            self.blocks += 1
        return self.actor.write(token, write)

    def tick(self, *, music_active, speech_active, duck_gain, elapsed):
        self._target_gain = duck_gain if speech_active else 1.0
        now = self.now_ns()
        if (self.speech_output is not None
                and (self.token is not None or speech_active or now <= self._idle_hold_ns)):
            # A stopped idle player has no timer consuming this socket. Never
            # fill its kernel queue with idle controls before the next utterance.
            self.speech_output.control(speech_active, duck_gain)
        if self.error:
            raise RuntimeError(self.error)
        if self.speech_output is not None:
            # The authenticated backend owns an output-only speech clock even
            # when the room has no music owner. Synthetic FIFO silence would
            # compete with that bed and make a paused input wait for its full
            # capacity before a fresh mix, aging the original packet anchor.
            # Actual music still enters only through accept() at its original P.
            return
        if self.actor is None or self.token is not None or self.route is None:
            return
        preparation = self.speech_preparation
        preparing_bed = bool(preparation and not preparation.retired and preparation.idle
                             and preparation.phase in {"waiting_for_mix", "waiting_for_negotiation", "ready"})
        if not self.speech and now > self._idle_hold_ns and not preparing_bed:
            self.writer.close()
            self._idle_next_ns = 0
            return
        if not self._idle_next_ns:
            self._idle_next_ns = now
        if self._idle_next_ns > now:
            return
        gap = now - self._idle_next_ns > 250_000_000
        if gap:
            self._idle_next_ns = now
        incarnation, session, epoch, generation = self.route
        if session != ZERO_UUID:
            return
        lead_ns = ((self.output_buffer_ms+100)*1_000_000 if self.speech_output is not None
                   else self.relay_delay_ns)
        packet = Packet(Kind.PCM, session, incarnation=incarnation, epoch=epoch, generation=generation,
                        frame_index=self._idle_frame, flags=FLAG_SPEECH_ONLY | (FLAG_GAP if gap else 0),
                        frames=960, pcm=bytes(3840), clock=Clock.MONOTONIC,
                        presentation_ns=self._idle_next_ns + lead_ns)
        def write():
            self.writer.write(packet if self.speech_output is not None
                              else replace(packet, pcm=self._mix(packet.pcm, packet.frames)))
            self._idle_frame += packet.frames
            self._idle_next_ns += 20_000_000
        self.actor.write_idle(write)

    def health(self):
        speech_input_active = self.now_ns() < self._speech_input_until_ns
        return {"ready": self.error is None,
                "audio_active": self.token is not None or bool(self.speech) or speech_input_active,
                "speech_input_active": speech_input_active,
                "music_gain": self._gain if self.speech_output is None else None,
                "music_target_gain": self._target_gain, "fifo_reader": self.writer.reader_present,
                "written_bytes": self.writer.written_bytes, "dropped_bytes": self.writer.dropped_bytes,
                "speech_dropped_frames": self.speech_dropped_frames, "native_blocks": self.blocks,
                "timing_relay_delay_ms": self.relay_delay_ns // 1_000_000,
                "output_buffer_ms": self.output_buffer_ms,
                **(self.speech_output.health() if self.speech_output is not None else {}),
                **(self.speech_preparation.receipt() if self.speech_preparation else {}),
                "clock_mapping_uncertainty_ns": self._last_mapping.uncertainty_ns if self._last_mapping else None,
                "native_group_id": str(UUID(bytes=self._last_packet.group)) if self._last_packet and self._last_packet.group != ZERO_UUID else None,
                "native_generation": self._last_packet.generation if self._last_packet else None,
                "music_media_recent": bool(self._last_native_ns
                    and 0 <= self.now_ns() - self._last_native_ns <= 1_000_000_000),
                "error": self.error}

    def close(self):
        self.writer.close()
        self.speech.clear()
        if self.speech_output is not None:
            self.speech_output.close()


class NativeHandle:
    def __init__(self, controller, connection=None):
        self.controller = controller
        self.connection = connection
        self.token = None
        self.generation = 1
        self.fence = None
        self.closed = False
        self.volume_base_revision = controller.control_revision
        self.last_volume = None
        self.receive_task = None
        self.receive_loop = None

    def _cancel_receive(self):
        task = self.receive_task
        if task is not None:
            # Closing a socket does not retire asyncio's selector entry. Its
            # numeric descriptor can immediately belong to a new RPC/socket,
            # while the old sock_recv still owns that entry and its cleanup.
            # Unregister while this exact socket still owns the descriptor;
            # remove_reader also cancels the old handle, so late read cleanup
            # cannot remove a successor's registration after descriptor reuse.
            if self.connection is not None and self.connection.fileno() >= 0:
                self.receive_loop.remove_reader(self.connection.fileno())
            task.cancel()
        return task

    def close_connection(self):
        self.closed = True
        self._cancel_receive()
        if self.connection is not None:
            self.connection.close()

    async def receive(self, maximum, timeout):
        if self.closed or self.receive_task is not None:
            raise TimingError("Native transport is closed or already receiving")
        self.receive_loop = asyncio.get_running_loop()
        task = asyncio.create_task(self.receive_loop.sock_recv(self.connection, maximum))
        self.receive_task = task
        try:
            return await asyncio.wait_for(task, timeout=timeout)
        finally:
            if self.receive_task is task:
                self.receive_task = None

    def abort(self, token):
        if self.token == token:
            self.close_connection()

    async def quiesce(self, token):
        if self.token != token:
            return
        self.closed = True
        task = self._cancel_receive()
        try:
            # This is the receive subtask, never the parent connection whose
            # finally may be waiting for the actor's ownership lock. Joining
            # the parent here would deadlock a native END/source transition.
            if task is not None:
                await asyncio.gather(task, return_exceptions=True)
        finally:
            # Cancellation/watchdog abort remains synchronous and safe: the
            # exact reader was unregistered before any descriptor closure.
            self.close_connection()

    def set_volume(self, token, volume):
        if self.token != token or self.closed:
            raise TimingError("Native volume belongs to another transport incarnation")
        self.last_volume = (volume, self.volume_base_revision, self.generation)
        self.controller.volume_event(token, self.generation, volume, self.volume_base_revision)


class NativeController:
    """Exact native callbacks, mixer writes and authenticated backend barrier."""
    def __init__(self, room_id, mixer, client, *, control_revision=1, control_volume=50):
        self.mixer, self.client = mixer, client
        self.handles = {}
        self.operation_generation = 0
        self.events = []
        self.control_revision = self._revision(control_revision)
        from .receiver_volume import ReceiverVolume
        self.receiver_volume = ReceiverVolume(self, control_volume)
        self._volume_changed = asyncio.Event()
        self._volume_task = None
        self.volume_bridge_error = None
        self.actor = SourceActor(room_id, mixer.fence, barrier=self.barrier)
        mixer.actor = self.actor
        self.closed = False
        self.server = None
        self.listener = None
        self.connections = set()
        self.ingress_fault = None
        self.music_startup = MusicStartupTrace()
        self._output_setup_lock = asyncio.Lock()
        self._warm_generation = 0
        self._warm_identity = None
        self._warm_connected = False
        self._warm_terminal = False

    @staticmethod
    def _revision(value):
        if type(value) is not int or not 1 <= value <= 2**63 - 1:
            raise RpcError("invalid_request", "Control revision must be an integer between 1 and INT64_MAX")
        return value

    def control_intent(self, revision):
        self.control_revision = max(self.control_revision, self._revision(revision))
        self.receiver_volume.intent(self.control_revision)
        return {"revision": self.control_revision}

    def volume_event(self, token, generation, volume, base_revision):
        event = {"event_id": str(uuid4()), "token": token.model_dump(),
                 "generation": generation, "volume": volume,
                 "base_revision": self._revision(base_revision)}
        if len(self.events) < 2:
            self.events.append(event)
        else:
            self.events[1] = event
        self._volume_changed.set()

    def acknowledge_volume(self, event_id):
        self.events = [event for event in self.events if event["event_id"] != event_id]

    async def start_volume_bridge(self, socket_path, launch_generation, *, rpc=call_rpc, retry_seconds=0.1):
        if (not isinstance(launch_generation, str) or len(launch_generation) != 32
                or any(char not in "0123456789abcdef" for char in launch_generation)):
            raise RpcError("invalid_request", "Native signal launch generation must be 32 lowercase hex characters")
        if self._volume_task is not None:
            raise RuntimeError("The native volume bridge is already running")
        async def forward():
            while not self.closed:
                self._volume_changed.clear()
                if self.events:
                    # Keep the first pending identity stable until durable ACK;
                    # only the second slot can coalesce newer phone intent.
                    event = self.events[0]
                    payload = {"launch_generation": launch_generation, **event}
                    try:
                        ack = await rpc(socket_path, "native-volume", payload, timeout=2)
                    except Exception as exc:
                        self.volume_bridge_error = type(exc).__name__
                    else:
                        if (isinstance(ack, dict) and ack.get("ok") is True
                                and ack.get("durable") is True and ack.get("acknowledged") is True
                                and ack.get("event_id") == event["event_id"]
                                and type(ack.get("accepted")) is bool):
                            self.acknowledge_volume(event["event_id"])
                            self.volume_bridge_error = None
                            continue
                        self.volume_bridge_error = "Invalid durable native volume acknowledgement"
                try:
                    await asyncio.wait_for(self._volume_changed.wait(), timeout=retry_seconds)
                except asyncio.TimeoutError:
                    pass
        self._volume_task = asyncio.create_task(forward())

    def begin_speech(self, identity, *, commit_required=False):
        if self.mixer.speech_output is None:
            return None
        preparation = SpeechPreparation(identity, now_ns=self.mixer.now_ns, commit_required=commit_required)
        self.mixer.begin_speech_preparation(preparation)
        return preparation

    async def prepare_speech(self, identity, preparation):
        if preparation is None:
            return None
        if self.mixer.speech_preparation is not preparation or preparation.identity is not identity:
            preparation.fail("session_replaced")
        snapshot = self.actor.snapshot()
        route = self.mixer.route
        operation = self.operation_generation
        if not snapshot["ready"] or route is None:
            preparation.fail("source_not_ready")
        incarnation, session, epoch, generation = route
        preparation.idle = session == ZERO_UUID
        body = {"incarnation": incarnation.hex(), "session_id": None if preparation.idle else session.hex(),
                "epoch": epoch, "generation": generation, "operation_generation": operation,
                "room_id": self.mixer.speech_output.room.hex(), "launch_generation": self.mixer.speech_output.launch.hex(),
                "speech_id": preparation.speech_id}
        def owned():
            state = self.actor.snapshot()
            return (not preparation.retired and self.mixer.speech_preparation is preparation
                    and state["ready"] and self.mixer.route == route and self.operation_generation == operation
                    and (state["owner"] is None) == preparation.idle)
        def admit(speech_id):
            if getattr(identity, "duck_on_prepare", False):
                self.mixer.speech_output.begin(speech_id, attack_ms=300, release_ms=600)
            else:
                self.mixer.speech_output.begin(speech_id)
        controller = self
        class SetupClient:
            async def request(self, method, path, **kwargs):
                if (path == "/api/player/shiri-speech-ready"
                        and kwargs.get("json", {}).get("action") == "prepare"):
                    async with controller._output_setup_lock:
                        return await controller.client.request(method, path, **kwargs)
                return await controller.client.request(method, path, **kwargs)
        return await complete_speech_startup(preparation, SetupClient(), body, owned=owned,
            bed=lambda value: None, send=self.mixer._send_speech,
            admit=admit)

    def negotiated_speech(self, identity):
        preparation = self.mixer.speech_preparation
        if preparation is None or preparation.identity is not identity or preparation.retired:
            raise RpcError("session_conflict", "Speech preparation ended during negotiation")
        preparation.negotiated.set()

    def commit_speech(self, identity):
        preparation = self.mixer.speech_preparation
        if preparation is None or preparation.identity is not identity:
            raise RpcError("session_conflict", "Speech preparation ended before negotiation")
        preparation.commit(self.mixer._send_speech)

    def retire_speech(self, identity):
        # Retirement is synchronous and exact; an old cleanup cannot erase the
        # successor prefix or manipulate its program/output sessions.
        return self.mixer.retire_speech_preparation(identity)

    async def retire_speech_backend(self, preparation, *, natural=False):
        if preparation is not None:
            await retire_backend(preparation, self.client, natural=natural)

    @staticmethod
    def _warm_id(value):
        if (type(value) is not str or len(value) != 32 or value == "0" * 32
                or any(char not in "0123456789abcdef" for char in value)):
            raise RpcError("invalid_request", "Connection warming requires an exact nonzero lease identity")
        return value

    def _warm_body(self, lease_id, action, deadline_ns=0):
        self._warm_id(lease_id)
        if self.mixer.speech_output is None:
            raise RpcError("unsupported", "Connection warming requires the native room binding")
        if self._warm_identity is None or self._warm_identity[0] != lease_id:
            if action != "acquire" and not (action == "release" and self._warm_identity is None):
                raise RpcError("session_conflict", "Another native connection lease owns this room")
            if self._warm_generation >= 2**63 - 1:
                raise RpcError("session_limit", "Native connection lease identities are exhausted")
            self._warm_generation += 1
            self._warm_identity = (lease_id, self._warm_generation)
            self._warm_connected = self._warm_terminal = False
        return {"room_id": self.mixer.speech_output.room.hex(),
                "launch_generation": self.mixer.speech_output.launch.hex(),
                "warm_id": lease_id, "lease_generation": self._warm_identity[1],
                "action": action, "deadline_monotonic_ns": deadline_ns}

    async def _warm_exchange(self, body, deadline_ns):
        remaining = (deadline_ns - self.mixer.now_ns()) / 1e9
        if remaining <= 0:
            raise TimeoutError("Connection preparation exceeded its finite control budget")
        reply = await asyncio.wait_for(self.client.request(
            "POST", "/api/player/shiri-warm", json=body), timeout=remaining)
        expected = set(body) | {"connected", "pending", "terminal", "prepared_monotonic_ns",
                                "expires_monotonic_ns", "output_count"}
        if (type(reply) is not dict or set(reply) != expected
                or any(type(reply.get(key)) is not type(value) or reply[key] != value
                       for key, value in body.items())
                or any(type(reply[key]) is not bool for key in ("connected", "pending", "terminal"))
                or any(type(reply[key]) is not int or not 0 <= reply[key] <= 2**63 - 1
                       for key in ("prepared_monotonic_ns", "expires_monotonic_ns"))
                or type(reply["output_count"]) is not int or not 0 <= reply["output_count"] <= 128
                or reply["connected"] and (reply["pending"] or reply["terminal"]
                    or not reply["output_count"] or not 0 < reply["prepared_monotonic_ns"] <= self.mixer.now_ns()
                    or reply["expires_monotonic_ns"] <= self.mixer.now_ns())):
            raise RpcError("audio_unavailable", "Native connection lease did not acknowledge its exact bounded identity")
        self._warm_connected = reply["connected"]
        self._warm_terminal = reply["terminal"]
        return {"state": "connected" if reply["connected"] else "degraded",
                **{key: reply[key] for key in expected - set(body)},
                "lease_id": body["warm_id"], "lease_generation": body["lease_generation"],
                "scope": "connection_only", "acoustic_ready": None}

    async def warm_connection(self, lease_id, deadline_monotonic_ns):
        """Prepare selected transports without speech, silence or music intent.

        Only this explicit acquire can start a connection. The backend owns a
        finite setup timer; its keepalive and lease timers never reconnect.
        """
        self._warm_id(lease_id)
        now = self.mixer.now_ns()
        if (type(deadline_monotonic_ns) is not int
                or not now < deadline_monotonic_ns <= min(2**63 - 1, now + 300_000_000_000)):
            raise RpcError("invalid_request", "Connection expiry must be within five minutes of admission")
        async with self._output_setup_lock:
            if self.closed or not self.actor.snapshot()["ready"]:
                raise RpcError("audio_unavailable", "This native room cannot prepare an output connection")
            existing = bool(self._warm_identity and self._warm_identity[0] == lease_id
                            and self._warm_connected and not self._warm_terminal)
            body = self._warm_body(lease_id, "acquire", deadline_monotonic_ns)
            if self._warm_terminal:
                raise RpcError("session_conflict", "This native connection lease has ended")
            began = self.mixer.now_ns()
            control_deadline = min(deadline_monotonic_ns, began + 3_000_000_000)
            # Reserve a bounded cancellation lane inside the same total budget.
            setup_deadline = min(control_deadline, began + 2_500_000_000)
            try:
                result = await self._warm_exchange(body, setup_deadline)
                while result["pending"] and not result["terminal"]:
                    await asyncio.sleep(.01)
                    result = await self._warm_exchange({**body, "action": "observe",
                                                       "deadline_monotonic_ns": 0}, setup_deadline)
                if not result["connected"]:
                    raise RpcError("audio_unavailable", "Selected room connections did not finish finite preparation")
                return result
            except BaseException:
                # A failed additional caller must not retire a connection
                # retained by an already admitted aggregate lease.
                if not existing:
                    await self._retire_warm_exact(body, control_deadline)
                raise

    async def _retire_warm_exact(self, body, control_deadline):
        request = {**body, "action": "release", "deadline_monotonic_ns": 0}
        async def retire():
            result = await self._warm_exchange(request, control_deadline)
            while result["pending"]:
                await asyncio.sleep(.01)
                result = await self._warm_exchange({**request, "action": "observe"}, control_deadline)
            return result
        task = asyncio.create_task(retire(), name="native-warm-retirement")
        interrupted = False
        while True:
            try:
                result = await asyncio.shield(task)
                break
            except asyncio.CancelledError:
                if task.cancelled():
                    raise
                interrupted = True
        if interrupted:
            raise asyncio.CancelledError
        return result

    async def observe_warm_connection(self, lease_id):
        async with self._output_setup_lock:
            body = self._warm_body(lease_id, "observe")
            return await self._warm_exchange(body, self.mixer.now_ns() + 3_000_000_000)

    async def adjust_warm_deadline(self, lease_id, deadline_monotonic_ns):
        """Change the aggregate bound without SETUP or reconnecting a speaker."""
        now = self.mixer.now_ns()
        if (type(deadline_monotonic_ns) is not int
                or not now < deadline_monotonic_ns <= min(2**63 - 1, now + 300_000_000_000)):
            raise RpcError("invalid_request", "Connection expiry must be within five minutes of admission")
        async with self._output_setup_lock:
            body = self._warm_body(lease_id, "deadline", deadline_monotonic_ns)
            return await self._warm_exchange(body, self.mixer.now_ns() + 3_000_000_000)

    async def release_warm_connection(self, lease_id):
        async with self._output_setup_lock:
            body = self._warm_body(lease_id, "release")
            return await self._retire_warm_exact(body, self.mixer.now_ns() + 3_000_000_000)

    async def _transition(self, owner):
        async with self._output_setup_lock:
            return await self._transition_outputs(owner)

    async def _transition_outputs(self, owner):
        self.operation_generation += 1
        operation = self.operation_generation
        incarnation, session, epoch, generation = owner
        body = {"incarnation": incarnation.hex(), "session_id": session.hex() if session != ZERO_UUID else None,
                "epoch": epoch, "generation": generation, "operation_generation": operation}
        self.music_startup.backend_started(owner, operation, self.mixer.now_ns())
        try:
            ack = await self.client.request("POST", "/api/player/shiri-source", json=body)
            if ack != body:
                raise TimingError("Output source barrier did not acknowledge the exact owner and operation")
            self.mixer.arm(owner)
        except BaseException:
            self.music_startup.backend_completed(owner, operation, self.mixer.now_ns(), acknowledged=False)
            raise
        self.music_startup.backend_completed(owner, operation, self.mixer.now_ns(), acknowledged=True)

    async def initialize(self):
        state = self.actor.snapshot()
        await self._transition((UUID(state["incarnation"]).bytes, ZERO_UUID, 0, 1))

    async def barrier(self, previous, next_token):
        state = self.actor.snapshot()
        if next_token is None:
            self.music_startup.retire(previous)
            owner = (UUID(state["incarnation"]).bytes, ZERO_UUID, previous.epoch if previous else state["epoch"], 1)
        else:
            handle = self.handles.get(next_token.session_id)
            if handle is None or handle.closed:
                raise TimingError("Output transition has no exact native transport handle")
            if handle.token is None:
                # Admission may fail/cancel inside the barrier. Bind the exact
                # candidate now so the actor's synchronous abort can close it
                # even before admit_native returns to begin().
                handle.token = next_token
            elif handle.token != next_token:
                raise TimingError("Native transport handle belongs to another source token")
            owner = (UUID(next_token.incarnation).bytes, UUID(next_token.session_id).bytes,
                     next_token.epoch, handle.generation)
            self.music_startup.start(next_token, handle.generation,
                                     getattr(handle, "music_requested_ns", self.mixer.now_ns()))
        await self._transition(owner)

    async def begin(self, packet, handle):
        if (packet.kind is not Kind.BEGIN or packet.generation != 1 or packet.epoch != 0
                or packet.incarnation != ZERO_UUID or packet.session == ZERO_UUID
                or packet.flags & FLAG_SPEECH_ONLY or not packet.flags & FLAG_AIRPLAY2
                or packet.session_id in self.handles or len(self.handles) >= 8):
            raise TimingError("Native admission requires a fresh exact AirPlay2 producer")
        handle.fence = StreamFence(packet.session)
        handle.music_requested_ns = self.mixer.now_ns()
        self.handles[packet.session_id] = handle
        try:
            handle.token = await self.actor.admit_native("airplay2", packet.session_id, handle)
        except BaseException:
            if handle.token is not None:
                handle.abort(handle.token)
            elif handle.connection is not None:
                # No proposed token exists if admission was refused before its
                # barrier; this exact never-admitted transport still must end.
                handle.close_connection()
            self.handles.pop(packet.session_id, None)
            raise
        self.music_startup.grant_ready(handle.token, handle.generation, self.mixer.now_ns())
        return self.grant(packet, handle)

    @staticmethod
    def grant(packet, handle):
        return replace(packet, kind=Kind.GRANT, frames=0, pcm=b"", epoch=handle.token.epoch,
                       incarnation=UUID(handle.token.incarnation).bytes, generation=handle.generation)

    def validate(self, packet, handle):
        token = handle.token
        if (handle.closed or token is None or packet.session_id != token.session_id
                or packet.incarnation != UUID(token.incarnation).bytes or packet.epoch != token.epoch):
            raise TimingError("Native event does not carry its exact admitted source token")

    async def message(self, packet, handle):
        self.validate(packet, handle)
        if packet.kind is Kind.FLUSH:
            handle.fence.flush(packet)
            handle.generation = packet.generation
            handle.music_requested_ns = self.mixer.now_ns()
            if not await self.actor.flush_native(handle.token):
                raise TimingError("An old native source cannot flush a successor")
            if handle.last_volume is not None and handle.last_volume[2] != handle.generation:
                # A queued volume from the preceding generation may arrive
                # after the flush. Reissue the latest phone intent with a NEW
                # receipt identity, retaining its original UI revision base.
                # A later UI edit must still win over this old phone intent.
                volume, base_revision, _old_generation = handle.last_volume
                self.volume_event(handle.token, handle.generation, volume, base_revision)
                handle.last_volume = (volume, base_revision, handle.generation)
            self.music_startup.grant_ready(handle.token, handle.generation, self.mixer.now_ns())
            return self.grant(packet, handle)
        if packet.generation != handle.generation:
            raise TimingError("Native callback belongs to a previous flush generation")
        if packet.kind is Kind.PCM:
            handle.fence.accept(packet)
            received_ns = self.mixer.now_ns()
            written, dropped = self.mixer.writer.written_bytes, self.mixer.writer.dropped_bytes
            if self.mixer.accept(packet, handle.token):
                self.music_startup.pcm(handle.token, packet, self.mixer._last_mapping,
                    received_ns=received_ns, completed_ns=self.mixer.now_ns(),
                    relay_delay_ns=self.mixer.relay_delay_ns, output_buffer_ms=self.mixer.output_buffer_ms,
                    written_bytes=self.mixer.writer.written_bytes-written,
                    dropped_bytes=self.mixer.writer.dropped_bytes-dropped)
        elif packet.kind is Kind.VOLUME:
            # Capture before waiting for the ownership lock. A UI edit arriving
            # during that wait must not become the old phone event's base.
            if self.receiver_volume.is_echo(handle.token, handle.generation, packet.frames):
                return None
            handle.volume_base_revision = self.control_revision
            await self.actor.volume_native(handle.token, packet.frames)
        elif packet.kind is Kind.END:
            handle.fence.end(packet)
            await self.actor.end_native(handle.token)
        else:
            raise TimingError("Unexpected native receiver message")
        return None

    async def _connection(self, connection):
        handle = NativeHandle(self, connection)
        loop = asyncio.get_running_loop()
        packet, previous, received_bytes, stage = None, None, 0, "receive"
        try:
            while not self.closed and not handle.closed:
                packet, previous, received_bytes, stage = None, None, 0, "receive"
                # An admitted phone may pause without sending PCM or controls.
                # EOF, exact owner revocation and controller shutdown retire its
                # registered reader; an idle deadline would disconnect that
                # valid source. Only a fresh unadmitted BEGIN stays timed.
                data = await handle.receive(HEADER_BYTES + MAX_FRAMES * 4 + 1,
                                            timeout=None if handle.token else 7)
                if not data:
                    break
                received_bytes, stage = len(data), "decode"
                if handle.fence is not None:
                    previous = {"generation": handle.fence.generation, "sequence": handle.fence.sequence,
                                "next_frame": handle.fence.next_frame, "presentation_ns": handle.fence.presentation,
                                "clock": handle.fence.clock.name.lower() if handle.fence.clock else None,
                                "gaps": handle.fence.gaps, "closed": handle.fence.closed}
                packet = Packet.decode(data)
                stage = "admit" if handle.token is None else packet.kind.name.lower()
                answer = await self.begin(packet, handle) if handle.token is None else await self.message(packet, handle)
                if answer is not None:
                    stage = "reply"
                    await asyncio.wait_for(loop.sock_sendall(connection, answer.encode()), timeout=0.3)
                    self.music_startup.grant_sent(handle.token, handle.generation, self.mixer.now_ns())
        except Exception as exc:
            if handle.token is not None and self.actor.owns(handle.token):
                self.ingress_fault = _fault_context(exc, stage, packet, previous,
                                                    received_bytes=received_bytes, now_ns=self.mixer.now_ns())
                self.mixer.error = f"Native timing ingress failed: {self.ingress_fault['reason']}"
                # Journal the exact gate before the source retirement/flush.
                log.warning("Native timing ingress rejected: %s", json.dumps(self.ingress_fault, separators=(",", ":")))
            # Exact connection failure retires only its own music owner. No
            # native reconnect can reuse its UUID or inherit a successor token.
            pass
        finally:
            try:
                if handle.token is not None:
                    await self.actor.end_native(handle.token)
            finally:
                if handle.token is not None and self.handles.get(handle.token.session_id) is handle:
                    self.handles.pop(handle.token.session_id, None)
                handle.close_connection()

    def _start_connection(self, connection):
        task = asyncio.create_task(self._connection(connection))
        self.connections.add(task)

        def finished(done):
            # A task canceled before its first instruction never enters the
            # coroutine's finally. Retire the exact accepted socket even then.
            connection.close()
            self.connections.discard(done)

        task.add_done_callback(finished)
        return task

    async def listen(self, path: Path, *, native_uid: int, mode=0o600):
        if not hasattr(socket, "SO_PEERCRED"):
            raise RuntimeError("Native timed ingress requires Linux peer credentials")
        try:
            info = path.lstat()
        except FileNotFoundError:
            info = None
        if info is not None:
            if not stat.S_ISSOCK(info.st_mode) or info.st_uid != os.getuid():
                raise RuntimeError("Refusing to replace another native receiver endpoint")
            path.unlink()
        self.listener = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
        self.listener.setblocking(False)
        self.listener.bind(str(path))
        path.chmod(mode)
        self.listener.listen(4)
        self._socket_path = path
        async def accept():
            loop = asyncio.get_running_loop()
            while not self.closed:
                connection, _ = await loop.sock_accept(self.listener)
                raw = connection.getsockopt(socket.SOL_SOCKET, socket.SO_PEERCRED, struct.calcsize("3i"))
                _pid, uid, _gid = struct.unpack("3i", raw)
                if uid != native_uid or len(self.connections) >= 8:
                    connection.close()
                    continue
                connection.setblocking(False)
                self._start_connection(connection)
        self.server = asyncio.create_task(accept())
        await self.receiver_volume.listen(path.with_name("volume.sock"), native_uid, mode)

    def health(self):
        from copy import deepcopy
        source = self.actor.snapshot()
        return {"source": source, "native_volume_events": deepcopy(self.events),
                "native_ingress_fault": deepcopy(self.ingress_fault),
                "music_startup": self.music_startup.snapshot(),
                "source_operation_generation": self.operation_generation,
                "control_revision": self.control_revision, "native_volume_bridge_error": self.volume_bridge_error,
                "receiver_volume": deepcopy(self.receiver_volume.result),
                **({"ready": False, "error": source["error"]} if source["error"] else {})}

    async def close(self):
        self.closed = True
        await self.receiver_volume.close()
        if self._volume_task is not None:
            self._volume_task.cancel()
            await asyncio.gather(self._volume_task, return_exceptions=True)
        if self.server:
            self.server.cancel()
            await asyncio.gather(self.server, return_exceptions=True)
        if self.listener:
            self.listener.close()
        for task in tuple(self.connections):
            task.cancel()
        if self.connections:
            await asyncio.gather(*self.connections, return_exceptions=True)
        await self.actor.close()
        if self.listener:
            self._socket_path.unlink(missing_ok=True)
