static int token_for(struct output_device*d){for(unsigned i=0;i<ARRAY_SIZE(outputs_cb_register);i++)if(outputs_cb_register[i].device_id==d->id&&outputs_cb_register[i].cb)return outputs_cb_register[i].token;return 0;}
static void deliver(int token,struct output_device*d,enum output_device_state state){outputs_cb(token,d->id,state);deferred_cb(-1,0,NULL);}
static void reset(void){
 shiri_source_wait_clear();assert(deadline_events==0);memset(outputs_cb_register,0,sizeof(outputs_cb_register));memset(&logical_cmd,0,sizeof(logical_cmd));command_base.current_cmd=NULL;
 playback_event_active=timer_calls=clock_reads=aborts=callback_token=pending_callbacks=command_completions=delayed_stops=0;
 timer_failure_call=clock_failure_read=output_fail=start_fail=seal_fail=arm_fail=peek_advances=starts=arms=flushes=stopped_sessions=0;peek_status=1;
 deadline_create_fail=deadline_add_fail=backend_stops=network_callbacks=0;
 fixture_now=(struct timespec){100,0};next_anchor=(struct timespec){100,750000000};player_tick_interval=(struct timespec){0,10000000};fixture_operation=2;fixture_state=1;shiri_armed=true;player_state=PLAY_PLAYING;
 pipe_source.data_kind=DATA_KIND_PIPE;pb_session.reading_now=(void*)&pipe_source;
 memset(&shiri_source_state,0,sizeof(shiri_source_state));shiri_source_state.initialized=true;
 shiri_source_state.last.owner.incarnation[0]=1;shiri_source_state.last.owner.session[0]=2;shiri_source_state.last.owner.epoch=1;shiri_source_state.last.owner.generation=1;shiri_source_state.last.operation_generation=2;
 for(int i=0;i<2;i++){memset(&devices[i],0,sizeof(devices[i]));devices[i].id=10+i;devices[i].name="fixture";devices[i].type_name="fixture";devices[i].selected=devices[i].advertised=1;devices[i].session=&devices[i];devices[i].state=OUTPUT_STATE_STREAMING;devices[i].stop_timer=&delayed[i];backend_flush[i]=backend_start[i]=1;delayed[i]=0;}
 devices[0].next=&devices[1];outputs_device_list=devices;
 assert(pb_timer_start()==0);pb_timer_native_anchored=true;pb_timer_native_anchor=(struct timespec){99,0};last_reason[0]=0;shiri_source_flush_failed=shiri_source_start_failed=0;
}
static struct shiri_source_param next_request(void){struct shiri_source_param p={0};p.request=shiri_source_state.last;p.request.operation_generation++;p.request.owner.generation++;return p;}
static enum command_state begin(struct shiri_source_param*p,int*r){enum command_state state=shiri_source_transition_begin(p,r);if(state==COMMAND_PENDING){assert(*r==1&&!cmdbase->current_cmd);logical_cmd=(struct command){.func=shiri_source_transition_begin,.arg=p,.pending=1};cmdbase->current_cmd=&logical_cmd;}return state;}
static void flush_warm_success(void){int t0=token_for(&devices[0]),t1=token_for(&devices[1]);deliver(t0,&devices[0],OUTPUT_STATE_CONNECTED);assert(command_completions==0);deliver(t1,&devices[1],OUTPUT_STATE_CONNECTED);}
static void cold(void){for(int i=0;i<2;i++){devices[i].session=NULL;devices[i].state=OUTPUT_STATE_STOPPED;}player_state=PLAY_STOPPED;pb_session.reading_now=NULL;assert(pb_timer_stop()==0);}
static void dispatch_tick(void){if(playback_event_active){int r=pb_timer_native_prepare();if(r<0)pb_abort();}}
int main(void){struct shiri_source_param p,q;int ret,t0,t1,oldop;
 reset();p=next_request();assert(begin(&p,&ret)==COMMAND_PENDING&&ret==1&&cmdbase->current_cmd==&logical_cmd&&!playback_event_active&&!shiri_armed);dispatch_tick();assert(aborts==0);flush_warm_success();assert(command_completions==1&&logical_cmd.ret==0&&!cmdbase->current_cmd&&!shiri_source_wait.active&&deadline_events==0&&shiri_armed&&!shiri_source_state.faulted&&playback_event_active&&pb_timer_native_waiting_for_pcm&&pb_timer_native_operation==3);
 puts("One exact logical command owns multi-output FLUSH -> warm START -> ARM; no timer abort or inter-phase lane release");
 peek_status=0;fixture_now=(struct timespec){121,0};dispatch_tick();assert(aborts==0&&shiri_armed&&playback_event_active&&pb_timer_native_waiting_for_pcm);peek_status=1;next_anchor=(struct timespec){121,450000000};assert(pb_timer_native_prepare()==0&&pb_timer_native_anchored&&!pb_timer_native_waiting_for_pcm&&timespec_cmp(pb_session.pts,next_anchor)==0);fixture_now=next_anchor;assert(pb_timer_native_prepare()==1);puts("Accepted phone pause >20 s retains exact gate, original future-P resume and zero volume requests");
 reset();cold();p=next_request();assert(begin(&p,&ret)==COMMAND_PENDING&&shiri_source_wait.phase==SHIRI_SOURCE_PHASE_START&&starts==2);t0=token_for(&devices[0]);t1=token_for(&devices[1]);deliver(t0,&devices[0],OUTPUT_STATE_CONNECTED);assert(command_completions==0);fixture_now=(struct timespec){102,999000000};deliver(t1,&devices[1],OUTPUT_STATE_CONNECTED);assert(command_completions==1&&logical_cmd.ret==0&&shiri_armed&&!shiri_source_state.faulted&&!playback_event_active);puts("Cold full selected-output START completes before first PCM admission within the single 3 s budget");
 reset();cold();p=next_request();assert(begin(&p,&ret)==COMMAND_PENDING);t0=token_for(&devices[0]);t1=token_for(&devices[1]);deliver(t0,&devices[0],OUTPUT_STATE_CONNECTED);fixture_now=(struct timespec){103,0};shiri_source_wait_timeout(-1,0,(void*)(uintptr_t)p.request.operation_generation);assert(command_completions==1&&logical_cmd.ret<0&&!cmdbase->current_cmd&&backend_stops==2&&!shiri_armed&&shiri_source_state.faulted&&!shiri_source_wait.active&&deadline_events==0&&!playback_event_active);deliver(t1,&devices[1],OUTPUT_STATE_CONNECTED);deliver(t0,&devices[0],OUTPUT_STATE_CONNECTED);assert(command_completions==1&&!cmdbase->current_cmd);puts("Lost/late START reply hits overall 3 s deadline, retires pending + already-ready exact tokens, frees logical lane once");
 /* Controlled successor fixture deliberately clears persistent source fault.
  * This proves late-token isolation, not automatic production retry. */
 for(int i=0;i<2;i++){int stop=token_for(&devices[i]);devices[i].session=NULL;deliver(stop,&devices[i],OUTPUT_STATE_STOPPED);}shiri_source_state.faulted=false;q=next_request();assert(begin(&q,&ret)==COMMAND_PENDING);oldop=p.request.operation_generation;shiri_source_wait_timeout(-1,0,(void*)(uintptr_t)oldop);deliver(t1,&devices[1],OUTPUT_STATE_CONNECTED);assert(command_completions==1&&cmdbase->current_cmd==&logical_cmd&&shiri_source_wait.remaining==2);deliver(token_for(&devices[0]),&devices[0],OUTPUT_STATE_CONNECTED);deliver(token_for(&devices[1]),&devices[1],OUTPUT_STATE_CONNECTED);assert(command_completions==2&&logical_cmd.ret==0);puts("Retired timer op and never-reused old protocol tokens cannot expire or complete a controlled successor attempt");
 reset();p=next_request();assert(begin(&p,&ret)==COMMAND_PENDING);t0=token_for(&devices[0]);t1=token_for(&devices[1]);fixture_now=(struct timespec){103,0};deliver(t0,&devices[0],OUTPUT_STATE_CONNECTED);assert(command_completions==1&&logical_cmd.ret<0&&backend_stops==2);deliver(t1,&devices[1],OUTPUT_STATE_CONNECTED);assert(command_completions==1);puts("A reply at deadline is failure even if the deadline event has not yet dispatched");
 reset();p=next_request();p.request.operation_generation++;assert(begin(&p,&ret)==COMMAND_END&&ret==SHIRI_SOURCE_CONFLICT&&playback_event_active&&shiri_armed&&flushes==0&&deadline_events==0&&!shiri_source_flush_failed&&!shiri_source_start_failed);
 reset();p.request=shiri_source_state.last;assert(begin(&p,&ret)==COMMAND_END&&ret==SHIRI_SOURCE_REPLAY&&playback_event_active&&shiri_armed&&flushes==0&&deadline_events==0);puts("Invalid/stale/replayed admission leaves source, timers, callbacks and deadline unchanged");
 reset();cold();devices[0].selected=devices[1].selected=0;p=next_request();assert(begin(&p,&ret)==COMMAND_END&&ret<0&&!shiri_armed&&shiri_source_state.faulted&&starts==0&&deadline_events==0);
 reset();cold();devices[0].session=&devices[0];devices[0].state=OUTPUT_STATE_STARTUP;backend_flush[0]=0;devices[1].selected=0;p=next_request();assert(begin(&p,&ret)==COMMAND_END&&ret<0&&!shiri_armed&&shiri_source_state.faulted&&starts==0);puts("No assigned output or an unfinished existing output session cannot produce a successful music grant");
 reset();p=next_request();assert(begin(&p,&ret)==COMMAND_PENDING);t0=token_for(&devices[0]);t1=token_for(&devices[1]);deliver(t0,&devices[0],OUTPUT_STATE_FAILED);deliver(t1,&devices[1],OUTPUT_STATE_CONNECTED);assert(command_completions==1&&logical_cmd.ret<0&&!shiri_armed&&!playback_event_active&&shiri_source_state.faulted);
 reset();cold();backend_start[0]=-1;p=next_request();assert(begin(&p,&ret)==COMMAND_PENDING);deliver(token_for(&devices[1]),&devices[1],OUTPUT_STATE_CONNECTED);assert(command_completions==1&&logical_cmd.ret<0&&!shiri_armed);puts("FLUSH and partial START failures never arm PCM, resurrect playback or strand cmdbase");
 reset();p=next_request();deadline_create_fail=1;assert(begin(&p,&ret)==COMMAND_END&&ret<0&&!shiri_armed&&!playback_event_active&&flushes==0&&deadline_events==0);
 reset();p=next_request();deadline_add_fail=1;assert(begin(&p,&ret)==COMMAND_END&&ret<0&&!shiri_armed&&!playback_event_active&&flushes==0&&deadline_events==0);
 reset();p=next_request();timer_failure_call=timer_calls+1;assert(begin(&p,&ret)==COMMAND_END&&ret<0&&!shiri_armed&&!playback_event_active&&flushes==0&&deadline_events==0);
 reset();p=next_request();seal_fail=1;assert(begin(&p,&ret)==COMMAND_END&&ret<0&&!shiri_armed&&!playback_event_active&&flushes==0&&deadline_events==0);
 reset();p=next_request();assert(begin(&p,&ret)==COMMAND_PENDING);timer_failure_call=timer_calls+1;flush_warm_success();assert(command_completions==1&&logical_cmd.ret<0&&!shiri_armed&&!playback_event_active&&shiri_source_state.faulted);puts("Deadline event, timer stop/seal and failed rearm cleanup leave no consuming event or armed input");
 reset();p=next_request();memset(p.request.owner.session,0,16);p.request.owner.generation=1;assert(begin(&p,&ret)==COMMAND_PENDING);flush_warm_success();assert(command_completions==1&&logical_cmd.ret==0&&starts==0&&stopped_sessions==1&&!playback_event_active&&!shiri_source_wait.active&&delayed[0]&&delayed[1]&&!shiri_source_state.faulted);puts("END skips network START, retires native timer and schedules both held outputs for bounded delayed release");
 reset();p=next_request();assert(begin(&p,&ret)==COMMAND_PENDING);logical_cmd.func=shiri_source_restart;fixture_now=(struct timespec){103,0};shiri_source_wait_timeout(-1,0,(void*)(uintptr_t)p.request.operation_generation);assert(command_completions==0&&cmdbase->current_cmd==&logical_cmd);logical_cmd.func=shiri_source_transition_begin;logical_cmd.arg=&q;assert(commands_exec_end_if(cmdbase,shiri_source_transition_begin,&p,-1)==0&&command_completions==0);logical_cmd.arg=&p;logical_cmd.pending=2;assert(commands_exec_end_if(cmdbase,shiri_source_transition_begin,&p,-1)==0&&command_completions==0);puts("Exact command completion refuses foreign function, foreign argument and nonlogical pending count");
 reset();pb_timer_native_anchored=false;next_anchor=fixture_now;assert(pb_timer_native_prepare()<0&&strstr(last_reason,"anchor_late"));reset();pb_timer_native_anchored=false;peek_status=0;fixture_now=pb_timer_native_wait_until;assert(pb_timer_native_prepare()<0&&strstr(last_reason,"anchor_timeout"));reset();pb_timer_native_anchored=false;peek_advances=1;peek_returns_at=next_anchor;assert(pb_timer_native_prepare()<0&&strstr(last_reason,"anchor_late"));puts("Cold 5 s first-anchor deadline and original late-P/fresh-clock rejection remain intact");
 shiri_source_wait_clear();assert(deadline_events==0);return 0;}
