# OwnTone config for %%ZONE_ID%% (runs in network namespace)

general {
	uid = "root"
	db_path = "%%GRP_DIR%%/state/songs3.db"
	logfile = "%%GRP_DIR%%/logs/owntone.log"
	loglevel = log
	admin_password = ""
	websocket_port = %%OWNTONE_WEBSOCKET_PORT%%
	cache_dir = "%%GRP_DIR%%/state/cache"
	cache_daap_threshold = 1000
	speaker_autoselect = no
	high_resolution_clock = yes
}

library {
	name = "%%DISPLAY_NAME%% Library"
	port = %%OWNTONE_PORT%%
	directories = { "%%GRP_DIR%%/pipes" }
	follow_symlinks = false
	filescan_disable = false
	pipe_autostart = true
	clear_queue_on_stop_disable = true
}

audio {
	type = "alsa"
	card = "default"
	nickname = "Local Output"
}

mpd {
	port = %%OWNTONE_MPD_PORT%%
}

streaming {
	sample_rate = 44100
	bit_rate = 192
}
